name: Dev Deploy
on: [push]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}

      #- name: Stop the server
      #  run: ssh dev 'sudo systemctl stop my-application'

      - name: Check out the source
        run: ssh dev 'cd repos/pbot-api && git fetch && git reset --hard origin/master'

      #- name: Start the server
      #  if: ${{ always() }}
      #  run: ssh dev 'sudo systemctl start my-application'
